# Generated by Django 4.2.2 on 2023-06-21 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('profile_photo', models.ImageField(upload_to='', verbose_name='Photo de profil')),
                ('follows', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='suit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
