# Generated by Django 4.2.2 on 2023-08-28 14:12

import authentication.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[authentication.models.User.validate_image], verbose_name='Photo de profil'),
        ),
    ]
