# Generated by Django 4.2.2 on 2023-06-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image_alter_stage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='image',
            new_name='picture',
        ),
    ]
