# Generated by Django 4.2.2 on 2023-06-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_image_picture_rename_image_recipe_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='picture',
        ),
    ]
