# Generated by Django 4.2.2 on 2023-08-28 13:52

import cloudinary.models
from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[recipes.models.Picture.validate_image], verbose_name='image'),
        ),
    ]
